# Generated by Django 5.2.8 on 2025-11-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
