# Generated by Django 5.2.8 on 2025-11-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_actor_image_alter_director_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='cast',
        ),
        migrations.AddField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='acted_in', to='films.film'),
        ),
        migrations.AddField(
            model_name='director',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='directed_by', to='films.film'),
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='actors', to='films.actor'),
        ),
    ]
