# Generated by Django 5.2.8 on 2025-11-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_actor_image_alter_director_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
